name: Test, Review and Generate APK
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:

  apk:
      name: Generate APK
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Setup Java JDK
          uses: actions/setup-java@v3.8.0
          with:
            java-version: 11
            distribution: 'temurin'

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

        - name: Upload APK to Github Artifacts
          uses: actions/upload-artifact@v3.1.1
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
  
  send-apk-on-telegram:
    name: Send Apk on Telegram
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download Stored Artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: "-677728639"
          token: "5915457647:AAGjdQ2IfM6SWg_iKYgIXuRVsEjA-WIJOBs"
          message: |
            Hi Guys,
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Created By @JahidHasanCo
          document: app-debug.apk
          photo: https://media.giphy.com/media/A6aHBCFqlE0Rq/giphy.gif
